#1400256139
-- WARNING!!!!
-- HOMUNCULUS MADE BEFORE THIS UPDATE WILL NOT BE AFFECTED.
-- YOU MUST WIPE (DELETE) ALL EXISTING HOMUNCULUS FROM YOUR
-- SAVE FILES!!!! FAILURE TO DO SO WILL ALLOW PLAYERS TO USE
-- PRE-EXISTING HOMUNCULUS TO BE USED TO EXPLOIT THINGS!!!!
TRUNCATE TABLE homunculus;
INSERT INTO `sql_updates` (`timestamp`) VALUES (1400256139);
